this is some sample Markdown

In [11]:
def changePills(o, v):
    print "value:",o,"-",v
    return;

for idx, val in enumerate(pills):
    changePills(idx, val)


value: 0 - 1
value: 1 - hey
value: 2 - 8828382


In [4]:
from numpy import matrix
birds = matrix([[100, 200, 300], [300, 200, 100], [0, 20, 30], [0, 0, 1]])
print birds

[[100 200 300]
 [300 200 100]
 [  0  20  30]
 [  0   0   1]]


In [151]:
%matplotlib inline
import pandas as pd
import json 
from itertools import groupby 
from collections import OrderedDict

In [174]:
df = pd.read_csv("keywords.csv")
df.fillna("", inplace=True)
print df.count()
print df

Maraschino    47
Lemon         47
Aqua          47
dtype: int64
         Maraschino           Lemon        Aqua
0               Hot             Tgt    Rollcall
1               ROZ          Target   New track
2               WEZ         New tgt       Track
3           Cleared      New target       Posit
4              Clrd     Next target   New track
5             9line        Next tgt     Transit
6            9-line            Grid       Onsta
7         Nine line             Grg      On-sta
8             Rifle        Building      On sta
9           Release            Bldg   Remaining
10         Wpn away        Compound     Off-tgt
11        Wpns away            Cmpd     Off tgt
12         Wpn-away           8line  Off target
13      Weapon-away          8-line      On-tgt
14           Impact      Eight line      On tgt
15           Splash      Eight-line   On target
16              TOF            Sdby     Eyes on
17   Time-of-flight           Stdby     Eyes-on
18   Time of flight     

In [176]:
#json_df = df.to_json(orient="columns")
jsons = []
for col in df:
    list = df[col].to_json(orient="values") 
    group = str(col)+":{ colors:"+list+"}";
    jsons.append(group)   
    #jsons.append(df[col].to_json(orient="values"))

jsons
#print jsons[0]

['Maraschino:{ colors:["Hot","ROZ","WEZ","Cleared","Clrd","9line","9-line","Nine line","Rifle","Release","Wpn away","Wpns away","Wpn-away","Weapon-away","Impact","Splash","TOF","Time-of-flight","Time of flight","Abort","Shift","Engage","Engagement","Launch","Survivor","Isolated person","Jack","Unlucky","Rescue","Recovery","SAM","Mud","SA","Bandit","Bogie","Spike","Shootdown","15-line","15 line","PJ","Threat","Popcorn","Gun","Missile","Execute","Egress","Recall"]}',
 'Lemon:{ colors:["Tgt","Target","New tgt","New target","Next target","Next tgt","Grid","Grg","Building","Bldg","Compound","Cmpd","8line","8-line","Eight line","Eight-line","Sdby","Stdby","Friendlies","BF","IED","Wpn","Weapon","ISARC","Condition","Authentication","Feet","Fence","Refuel","Texaco","Tanker","RV","Helo","Helicopter","ARCT","TOT","Bingo","Joker","","","","","","","","",""]}',
 'Aqua:{ colors:["Rollcall","New track","Track","Posit","New track","Transit","Onsta","On-sta","On sta","Remaining","Off-tgt","Off tgt","Of